[profile.default]
optimizer = true
optimizer_runs = 1000000
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
evm_version = "cancun"
solc = "0.8.26"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
base_sepolia = "${RPC_URL}"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }
